# Generated by Django 4.1 on 2024-03-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customerdetail_ingredient_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='phone',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
